In [1]:
from cosmograph_widget import Cosmograph
import pandas as pd
from IPython.display import display

In [2]:
points = pd.DataFrame([
  { 'id': '1', 'color': '#88C6FF' },
  { 'id': '2', 'color': '#FF99D2' },
  { 'id': '3', 'color': '#E3116C' },
])
points

  id    color
0  1  #88C6FF
1  2  #FF99D2
2  3  #E3116C

In [3]:
links = pd.DataFrame([
  { 'source': '1', 'target': '2' },
  { 'source': '1', 'target': '3' },
  { 'source': '2', 'target': '3' },
])
links

  source target
0      1      2
1      1      3
2      2      3

In [4]:
Cosmograph(points=points, links=links,
   point_id_by='id',
   point_size=6,
   point_color_by='color',
   point_color_strategy='actualColor',
   link_source_by='source',
   link_target_by='target',
   simulation_decay=20,
)

Cosmograph(background_color=None, focused_point_ring_color=None, hovered_point_ring_color=None, link_color=Non…